name: Send APK to Diawii
on:
  push:
    branches:
      - 'development'
  workflow_dispatch:

jobs:
  build:
    name: Send APK to Diawii
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Grant Permission to Execute
        run: chmod +x gradlew
      
            # Run Build Project
      - name: Build gradle project
        run: ./gradlew build
        
      - name: Build debug APK
        run: ./gradlew assembleDebug
        
      # - name: Upload APK to Github Artifacts
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: app
      #     path: app/build/outputs/apk/debug/app-debug.apk
      - uses: Tlaster/android-sign@v1.2.2
        name: Sign app APK
        with:
          releaseDirectory: |
            ./app/build/outputs/apk/debug
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          output: ./app/build/debug/signed
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload APK to Diawii
        id: Upload_APK
        uses: rnkdsh/action-upload-diawi@v1.5.4
        with:
          token: ${{ secrets.DIAWI_TOKEN }}
          file: ./app/build/debug/signed/app-debug-signed.apk
          comment: ${{ github.event.head_commit.message }}
                    
      - name: Send Notification
        uses: northwang-lucky/chatbot-webhook-client@v1.1.1
        with:
          app: DingTalk
          webhook: ${{ secrets.DING_TALK_HOOK }}
          secret: ${{ secrets.DING_TAIK_SECRET }}
          template: >-
            {
              "msgtype": "link",
              "link": {
                "title": "Android Installer",
                "text": "Debug version 110 tap link to download",
                "picUrl": "${{steps.Upload_APK.outputs.qrcode}}",
                "messageUrl": "${{steps.Upload_APK.outputs.url}}"
                }
            }
